[tool.poetry]
name = "virtual-assistant"
version = "0.1.0"
description = "Assistente virtuale con Chainlit, OpenAI e Resend"
authors = ["Michele Scommegna"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
chainlit = "^1.3.2"
openai = "^1.109.1"
resend = "^2.43.0"
python-dotenv = "^1.2.3"
pydantic = "2.8.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.masonry.api"